-- -- CREATE TABLE pgpromise();
-- DROP TABLE pgpromise;
-- CREATE TABLE pgpromise
-- (
--     id SERIAL NOT NULL PRIMARY KEY,
--     name varchar
-- (20),
--     city varchar
-- (20)
-- );
-- SELECT * FROM test WHERE name = 'Veronica'; SELECT --'